# Default values for api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 2
environment: pro
autoscaler:
  enabled: true
disruptionbudget:
  enabled: true
ingress:
  # Used to create an Ingress record.
  records:
    - host: api.prod.ovid-project.com
resources:
  limits:
    cpu: 1000m
    memory: 1500Mi
  requests:
    cpu: 100m
    memory: 512Mi
endpoints:
  ticketing: https://masmovil-prod-prod.apigee.net/masmovil/v1
  security: https://masmovil-prod-prod.apigee.net/masmovil/v1
